services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: |
          apt-get update && apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-bad1.0-0 \
            libavif13 \
            libenchant-2-2 \
            libsecret-1-0 \
            libmanette-0.2-0 \
            libgles2 \
            && pip install -r requirements.txt \
            && playwright install-deps \
            && playwright install chromium
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
